# Generated by Django 4.2.4 on 2023-09-12 12:58

import borrowings.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(
                        auto_now_add=True,
                        validators=[borrowings.models.validate_future_date],
                    ),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date(2023, 9, 19),
                        null=True,
                        validators=[borrowings.models.validate_future_date],
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[borrowings.models.validate_future_date],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing",
                        to="library.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
