# Generated by Django 4.2.4 on 2023-09-01 15:06

import borrowings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[borrowings.models.validate_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                auto_now_add=True, validators=[borrowings.models.validate_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(validators=[borrowings.models.validate_future_date]),
        ),
    ]
