# Generated by Django 4.2.4 on 2023-09-05 12:28

import borrowings.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("borrowings", "0003_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowing",
                to="library.book",
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 12, 12, 28, 48, 103568, tzinfo=datetime.timezone.utc
                ),
                validators=[borrowings.models.validate_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
