# Generated by Django 4.2.4 on 2023-09-11 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0004_borrowing_is_active_alter_borrowing_book_and_more"),
        ("borrowings", "0005_alter_borrowing_expected_return_date"),
    ]

    operations = []
