# Generated by Django 4.2.4 on 2023-09-11 15:37

import borrowings.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0006_merge_20230911_1359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2023, 9, 18),
                null=True,
                validators=[borrowings.models.validate_future_date],
            ),
        ),
    ]
